const portfolioData = {
    id: {
        name: "Revaldo Anjennu Rillif Anderson",
        email: "revaldoanjennurillifanderson@gmail.com",
        photo: "public/prf.webp",
        nav_home: "Home",
        nav_skills: "Tentang Saya",
        nav_projects: "Karya Saya",
        hero_title_1: "Hello I am",
        hero_title_2: "Revaldo Anderson",
        hero_desc: "Saat ini berstatus sebagai Pelajar dan merupakan Mantan Siswa Teknik Instalasi Tenaga Listrik di SMK Kemala Bhayangkari 1 Jakarta",
        hero_btn: "Eksplorasi",
        hero_sub_left: "Developer Pemula",
        hero_sub_right: "Berbasis di Jakarta",
        about_p1: "Saya <span class=\"text-zinc-800 font-bold\">Revaldo</span>, seorang lulusan baru dari jurusan <span class=\"text-zinc-800 font-bold\">Teknik Instalasi Tenaga Listrik (TITL)</span> di SMK Kemala Bhayangkari 1 Jakarta.",
        about_p2: "Meskipun berlatar belakang kelistrikan, saya memiliki ketertarikan besar dalam dunia teknologi dan saat ini sedang berfokus mempelajari pemrograman untuk mengejar karir sebagai <span class=\"text-zinc-800 font-bold\">Fullstack Developer</span>.",
        quote_phrases: [
            "Dari merangkai sirkuit hingga menulis baris kode. ",
            "Menjembatani logika kelistrikan ",
            "dengan arsitektur perangkat lunak modern, ",
            "saat ini sedang mempelajari pengembangan fullstack ",
            "digerakkan oleh presisi teknis, sistem terstruktur, ",
            "dan hasrat untuk membangun solusi digital."
        ],
        about_btn: "Lihat karya saya",
        pj_title_1: "Karya",
        pj_title_2: "Pilihan",
        pj_subheadline: "Menjembatani logika kelistrikan dan rekayasa perangkat lunak melalui",
        pj_dark_slide_t0: "Electrical System",
        pj_dark_card_t0_0: "Star-Delta Starter",
        pj_dark_card_d0_0: "Kontrol daya motor industri.",
        pj_dark_card_t0_1: "PLC Smart Relay",
        pj_dark_card_d0_1: "Otomasi motor Forward-Reverse.",
        pj_dark_slide_t1: "Backend System",
        pj_dark_card_t1_0: "REST API Server",
        pj_dark_card_d1_0: "Sistem API berkinerja tinggi.",
        pj_dark_card_t1_1: "Database Architecture",
        pj_dark_card_d1_1: "Skema basis data terstruktur.",
        pj_dark_slide_t2: "Web Design",
        pj_dark_card_t2_0: "Creative Frontend",
        pj_dark_card_d2_0: "Antarmuka digital interaktif.",
        pj_dark_card_t2_1: "Responsive UI/UX",
        pj_dark_card_d2_1: "Tata letak ramah seluler.",
        dark_expander_label: "Karya Saya",
        footer_headline: "Portfolio engineering dengan karya praktis dan eksekusi rapi.",
        footer_desc: "Terbuka untuk diskusi proyek, review portofolio, dan kolaborasi teknis.",
        back_to_top: "Kembali ke atas",
        all_rights_reserved: "Hak cipta dilindungi.",
        close_detail: "Tutup detail",
        pj_list: [
            {
                t: "Electrical System",
                d: "Perancangan kontrol panel & sistem kelistrikan Star-Delta.",
                full_d: "Mengembangkan sistem kendali motor industri menggunakan sirkuit Star-Delta dan sirkuit PLC Forward-Reverse berbasis Smart Relay untuk efisiensi daya listrik.",
                img: "public/elec.png",
                tg: ["Electrical", "PLC", "Control Panel"]
            },
            {
                t: "Sistem Backend",
                d: "Pembangunan arsitektur API server yang cepat dan aman.",
                full_d: "Membangun sistem API RESTful berkinerja tinggi menggunakan Node.js dan Express, dengan integrasi database terstruktur untuk memastikan skalabilitas dan keamanan data.",
                img: "public/back.webp",
                tg: ["Node.js", "Express", "REST API", "Database"]
            },
            {
                t: "Desain Web",
                d: "Antarmuka digital interaktif dengan transisi mulus.",
                full_d: "Mendesain dan memprogram antarmuka web interaktif yang mengutamakan estetika premium, mikro-animasi menggunakan GSAP, serta performa maksimal yang ramah seluler.",
                img: "public/web.webp",
                tg: ["Frontend", "GSAP", "UI/UX", "Tailwind"]
            }
        ]
    },
    en: {
        name: "Revaldo Anjennu Rillif Anderson",
        email: "revaldoanjennurillifanderson@gmail.com",
        photo: "public/prf.webp",
        nav_home: "Home",
        nav_skills: "About me",
        nav_projects: "My work",
        hero_title_1: "Hello I am",
        hero_title_2: "Revaldo Anderson",
        hero_desc: "Currently a Student and previously majored in Electrical Installation Engineering at SMK Kemala Bhayangkari 1 Jakarta",
        hero_btn: "Explore",
        hero_sub_left: "Fresh Developer",
        hero_sub_right: "Based in Jakarta",
        about_p1: "I'm <span class=\"text-zinc-800 font-bold\">Revaldo</span>, a fresh graduate majoring in <span class=\"text-zinc-800 font-bold\">Electrical Power Installation Engineering (TITL)</span> from SMK Kemala Bhayangkari 1 Jakarta.",
        about_p2: "Despite my electrical background, I have a strong passion for technology and am currently learning programming to pursue a career as a <span class=\"text-zinc-800 font-bold\">Fullstack Developer</span>.",
        quote_phrases: [
            "From wiring circuits to writing code. ",
            "Bridging the gap between electrical logic ",
            "and modern software architecture, ",
            "currently learning fullstack development ",
            "driven by technical precision, clean systems, ",
            "and a passion for building digital solutions."
        ],
        about_btn: "Let's see my work",
        pj_title_1: "Selected",
        pj_title_2: "Works",
        pj_subheadline: "Bridging electrical logic and software engineering through",
        pj_dark_slide_t0: "Electrical System",
        pj_dark_card_t0_0: "Star-Delta Starter",
        pj_dark_card_d0_0: "Industrial motor power control.",
        pj_dark_card_t0_1: "PLC Smart Relay",
        pj_dark_card_d0_1: "Forward-Reverse motor automation.",
        pj_dark_slide_t1: "Backend System",
        pj_dark_card_t1_0: "REST API Server",
        pj_dark_card_d1_0: "High-performance API systems.",
        pj_dark_card_t1_1: "Database Architecture",
        pj_dark_card_d1_1: "Structured database schemas.",
        pj_dark_slide_t2: "Web Design",
        pj_dark_card_t2_0: "Creative Frontend",
        pj_dark_card_d2_0: "Interactive user interfaces.",
        pj_dark_card_t2_1: "Responsive UI/UX",
        pj_dark_card_d2_1: "Mobile-first digital layouts.",
        dark_expander_label: "My Works",
        footer_headline: "Engineering portfolio with practical work and clean execution.",
        footer_desc: "Available for project discussions, portfolio reviews, and technical collaboration.",
        back_to_top: "Back to top",
        all_rights_reserved: "All rights reserved.",
        close_detail: "Close detail",
        pj_list: [
            {
                t: "Electrical System",
                d: "Design of control panels & Star-Delta electrical systems.",
                full_d: "Developing industrial motor control systems using Star-Delta circuits and Smart Relay-based PLC Forward-Reverse circuits for power efficiency.",
                img: "public/elec.png",
                tg: ["Electrical", "PLC", "Control Panel"]
            },
            {
                t: "Backend System",
                d: "Building fast, secure server API architecture.",
                full_d: "Building high-performance RESTful API systems using Node.js and Express, with structured database integration to ensure scalability and data security.",
                img: "public/back.webp",
                tg: ["Node.js", "Express", "REST API", "Database"]
            },
            {
                t: "Web Design",
                d: "Interactive digital interfaces with smooth transitions.",
                full_d: "Designing and programming interactive web interfaces prioritizing premium aesthetics, GSAP micro-animations, and mobile-friendly peak performance.",
                img: "public/web.webp",
                tg: ["Frontend", "GSAP", "UI/UX", "Tailwind"]
            }
        ]
    }
};
